#!/bin/bash
set -e

echo -e "\n--- Install Python 3.5 ---\n"
sudo add-apt-repository ppa:fkrull/deadsnakes -y
sudo apt-get update
sudo apt-get install -y python3.5

echo -e "\n--- Install Python Dependencies ---\n"
sudo python3.5 -m pip install -r /vagrant/requirements.txt
